comment: "This issue is closed because it does not meet our issue template. Please read it. Nach basanti"
issueConfigs:
- content:
  - "Describe the BUG"
  - "Steps To Reproduce"
  - "Expected Behavior"
  - "Current Behavior"

- content:
  - "USE CASE"
  - "Expected behavior"
  - "Additional context"
